# Compiler
CC=ocamlopt
# ocamlopt: platform-specific, faster
# ocamlc: platform-independent intermediate representation, run with ocamlrun

# Main file
SRC=samples.ml

build: $(SRC)
	$(CC) $(SRC)
